language: php

sudo: false

php:
  - 5.6

git:
  submodules: false
  depth: 10

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --optimize-autoloader --prefer-source --no-interaction --dev
  - npm install

script:
  - ./node_modules/.bin/gulp --production
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpcs --standard=PSR2 app/
